liqster_mq:
    resource: "@LiqsterMQBundle/Controller/"
    type:     annotation
    prefix:   /

liqster_home_page_notification:
    resource: "@LiqsterHomePageBundle/Controller/NotificationController.php"
    type:     annotation
    prefix:   /

liqster_payment_default:
    resource: "@LiqsterPaymentBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

liqster_home_page_result:
    resource: "@LiqsterHomePageBundle/Controller/ResultController.php"
    type:     annotation

liqster_home_page_account:
    resource: "@LiqsterHomePageBundle/Controller/AccountController.php"
    type:     annotation

liqster_home_page:
    resource: "@LiqsterHomePageBundle/Controller/DefaultController.php"
    type:     annotation

liqster_profile_page:
    resource: "@LiqsterHomePageBundle/Controller/ProfileController.php"
    type:     annotation

liqster_api:
    resource: "@LiqsterHomePageBundle/Controller/ApiController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

liqster_uset:
    resource: "@LiqsterUserBundle/Controller"
    type:     annotation
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /C7AD44CBAD762A5DA0A452F9E854FDC1E0E7A52A38015F23F3EAB1D80B931DD472634DFAC71CD34EBC35D16AB7FB8A90C81F975113D6C7538DC69DD8DE9077EC
