liqster_home_page_account:
    resource: "@LiqsterHomePageBundle/Controller/AccountController.php"
    type:     annotation

liqster_home_page:
    resource: "@LiqsterHomePageBundle/Controller/DefaultController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
