liqster_admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

liqster_payment_default:
    resource: "@LiqsterPaymentBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

liqster_home_page_result:
    resource: "@LiqsterHomePageBundle/Controller/ResultController.php"
    type:     annotation

liqster_home_page_account:
    resource: "@LiqsterHomePageBundle/Controller/AccountController.php"
    type:     annotation

liqster_home_page:
    resource: "@LiqsterHomePageBundle/Controller/DefaultController.php"
    type:     annotation

liqster_profile_page:
    resource: "@LiqsterHomePageBundle/Controller/ProfileController.php"
    type:     annotation

liqster_api:
    resource: "@LiqsterHomePageBundle/Controller/ApiController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
