# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    cron.resolver.class:        Cron\CronBundle\Cron\Resolver
    cron.manager.class:         Cron\CronBundle\Cron\Manager
    cron.command_builder.class: Cron\CronBundle\Cron\CommandBuilder
    cron.executor.class:        Cron\Executor\Executor

services:
    cron.resolver:
        class: "%cron.resolver.class%"
        arguments: ["@cron.manager", "@cron.command_builder", "%kernel.root_dir%"]
    cron.manager:
        class: "%cron.manager.class%"
        arguments: ["@doctrine"]
    cron.executor:
        class: "%cron.executor.class%"
    cron.command_builder:
        class: "%cron.command_builder.class%"
        arguments: ["%kernel.environment%"]

    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }